In [1]:
#!/usr/bin/python3

# num_GPU = 
# mem_growth = True

import tensorflow as tf
print('Tensorflow version: ', tf.__version__)

# gpus = tf.config.experimental.list_physical_devices("GPU")
# print('Number of GPUs available :', len(gpus))

# tf.config.experimental.set_visible_devices(gpus[num_GPU], 'GPU')
# tf.config.experimental.set_memory_growth(gpus[num_GPU], mem_growth)
# print('Used GPU: {}. Memory growth: {}'.format(num_GPU, mem_growth))

import numpy as np
import pickle
from tqdm import tqdm
from tensorflow.keras import Model
import scipy.io as sio

Tensorflow version:  2.5.0


In [2]:
x = np.load('x.npy')

In [10]:
x

array([[ 0.30426362-0.0693095j ],
       [ 0.05612145+0.09490497j],
       [-0.8720521 -0.09757537j],
       ...,
       [ 0.50623053+0.36076304j],
       [-0.09024484-0.79021734j],
       [ 0.1194677 -0.5088505j ]], dtype=complex64)

In [5]:
y_t = tf.math.tanh(x)

In [6]:
y_t

<tf.Tensor: shape=(2048, 1), dtype=complex64, numpy=
array([[ 0.2965077 -0.06334417j],
       [ 0.056569  +0.09488904j],
       [-0.7058089 -0.04935708j],
       ...,
       [ 0.5174126 +0.28611225j],
       [-0.18026449-0.99330395j],
       [ 0.15522179-0.5475547j ]], dtype=complex64)>

In [7]:
y = np.load('y.npy')

In [8]:
y

array([[-0.15500456-0.7868455j ],
       [ 1.1112366 +0.1863279j ],
       [ 0.08348078+0.718619j  ],
       ...,
       [ 0.35782284+0.37048906j],
       [ 1.036837  +0.05657822j],
       [-0.19314411-0.18956658j]], dtype=complex64)

In [ ]:
# if __name__ == '__main__':
#     # PA nonlinearity simple model
#     # Input: x(t) = a(t)*exp(i*theta(t))
#     # Output y(t) = A(a(t))*exp(i*（theta(t)+phi(a(t))）)
#     # Where A(a(t)) = alpha_A*a(t)/(1+beta_A*(a(t)^2))
#     # and phi(a(t)) = alpha_p*(a(t)^2)/(1+beta_p*(a(t)^2))
#     # Equivalently C(a(t)) = A_1(a(t))*exp(i*phi(a(t)))
#     # where A_1(a(t)) = alpha_A/(1+beta_A*(a(t)^2))
#     # normal_factor = alpha_A/(1+beta_A);
#     # alpha_A = 2.996048; beta_A = 0.515222.
#     # alpha_p = 5.544818e-14; beta_p = 141.637485
    
#     # x = (tf.random.normal([10,1], mean=0.0, stddev=1.0), tf.random.normal([10,1], mean=0.0, stddev=1.0))
#     # x = tf.complex(x[0], x[1])
#     a_t = tf.math.abs(x)
#     # PA non-lineaerity parameters
#     alpha_A = tf.constant(2.996048, tf.float32)
#     beta_A = tf.constant(0.515222, tf.float32)
#     alpha_p = tf.constant(5.544818e-14, tf.float32)
#     beta_p = tf.constant(141.637485, tf.float32)
#     complex_i = tf.constant(1j,dtype=tf.complex64)
#     normal_factor = alpha_A/(1+beta_A)
    
#     C_a_t = alpha_A/(1+beta_A*tf.math.square(a_t))/normal_factor
#     phi_a_t = alpha_p*tf.math.square(a_t)/(1+beta_p*tf.math.square(a_t))
#     C_a_t = tf.complex(tf.math.cos(phi_a_t)*C_a_t, tf.math.sin(phi_a_t)*C_a_t)
#     y_t = C_a_t*x

In [12]:
con = np.load('_con.npy')

In [13]:
xint = tf.math.argmin(tf.square(tf.abs(y_t - con)), axis=0, output_type=tf.int32)

In [14]:
xint

<tf.Tensor: shape=(64,), dtype=int32, numpy=
array([148, 253,  32, 148,  19,  56,  90,  39,  30,  31,  19,  69, 116,
        70,  14,  88,  36,  65,   8,   0,   9, 228, 148, 182,  10, 114,
       148,  39,   9,  48, 253,   3,  21,   1, 185, 148,   4,  52,  12,
        52,  21,  24, 104,  21, 148,  52,  63,  37,  45,  11,  40, 185,
         7, 107,  63, 148,  32,  40,  39,  40,  11, 148, 104,  68],
      dtype=int32)>

In [15]:
x_count = tf.math.bincount(xint)

In [16]:
x_count

<tf.Tensor: shape=(254,), dtype=int32, numpy=
array([1, 1, 0, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 0, 1, 0, 0, 0, 0, 2, 0, 3,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 0, 3, 3, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], dtype=int32)>

In [27]:
def gaussianMI(x, y, constellation, M):
    """
        Computes mutual information with Gaussian auxiliary channel assumption and constellation with uniform porbability distribution

        x: (1, N), N normalized complex samples at the transmitter, where N is the batchSize/sampleSize
        y: (1, N), N normalized complex observations at the receiver, where N is the batchSize/sampleSize
        constellation: (1, M), normalized complex constellation of order M
        
        Transcribed from Dr. Tobias Fehenberger MATLAB code.
        See: https://www.fehenberger.de/#sourcecode
    """
    print(x)
    if len(constellation.shape) == 1:
        constellation = tf.expand_dims(constellation, axis=0)
    if len(y.shape) == 1:
        y = tf.expand_dims(y, axis=0)
    if len(x.shape) == 1:
        x = tf.expand_dims(x, axis=0)
    if y.shape[0] != 1:
        y = tf.linalg.matrix_transpose(y)
    if x.shape[0] != 1:
        x = tf.linalg.matrix_transpose(x)
    if constellation.shape[0] == 1:
        constellation = tf.linalg.matrix_transpose(constellation)

    N = tf.cast( tf.shape(x)[1], dtype = tf.float64 )

    PI = tf.constant( np.pi,dtype = tf.float64)
    REALMIN = tf.constant( np.finfo(float).tiny, dtype = tf.float64 )
    print(tf.square(x - constellation))
    xint = tf.math.argmin(tf.square(tf.abs(x - constellation)), axis=0, output_type=tf.int32)
    print(xint)
    x_count = tf.math.bincount(xint,minlength=65)
    # if x_count.shape[0] < 64 :
    #   loop = 64 - x_count.shape[0]
    #   print(loop)
    #   for i in range(loop):
    #     x_count = tf.concat([x_count,[0]],0)
    print(x_count)
    # x_count = tf.ensure_shape(x_count, (M,))
    # print(x_count)
    # P_X = tf.cast(x_count, dtype = tf.float64) / N
        
    # N0 = tf.reduce_mean( tf.square( tf.abs(x-y) ) )
    
    # qYonX = 1 / ( PI*N0 ) * tf.exp( ( -tf.square(tf.math.real(y)-tf.math.real(x)) -tf.square(tf.math.imag(y)-tf.math.imag(x)) ) / N0 )
    
    # qY = []
    # for ii in np.arange(M):
    #     temp = P_X[ii] * (1 / (PI * N0) * tf.exp( ( -tf.square(tf.math.real(y)-tf.math.real(constellation[ii,0])) -tf.square(tf.math.imag(y)-tf.math.imag(constellation[ii,0])) ) / N0) )
    #     qY.append(temp)
    # qY = tf.reduce_sum( tf.concat(qY, axis=0), axis=0)
            
    # MI = 1 / N * tf.reduce_sum( log2( tf.math.maximum(qYonX, REALMIN) / tf.math.maximum(qY, REALMIN) ) )
    
    # return MI

In [28]:
gaussianMI(y_t,y,con,64)

tf.Tensor(
[[ 0.2965077 -0.06334417j]
 [ 0.056569  +0.09488904j]
 [-0.7058089 -0.04935708j]
 ...
 [ 0.5174126 +0.28611225j]
 [-0.18026449-0.99330395j]
 [ 0.15522179-0.5475547j ]], shape=(2048, 1), dtype=complex64)
tf.Tensor(
[[ 4.210892  +7.50659287e-01j  3.197165  +1.23925686e+00j
   1.0804586 +4.15029466e-01j ...  4.9204187 +2.42538810e+00j
   1.9478216 -2.36796093e+00j  3.5906987 -1.15905905e+00j]
 [-0.06616014+1.47116172e+00j  0.64638704+1.55076933e+00j
   2.6438992 +3.17804146e+00j ...  0.10307518+6.51912510e-01j
  -1.535476  +4.75404978e+00j -0.89315164+2.66796017e+00j]
 [ 0.05588185-1.03755645e-01j  0.17414384-3.57427388e-01j
   1.6462224 -4.92893457e-01j ... -0.27067482-7.75845423e-02j
   0.02678627+1.16333055e+00j  0.09512634+2.68751383e-01j]
 ...
 [ 4.3521004 +2.19641209e-01j  3.3665552 +7.78867304e-01j
   1.1717376 +1.44484818e-01j ...  5.163982  +1.85579884e+00j
   1.8225787 -2.82512236e+00j  3.598886  -1.67933750e+00j]
 [-0.09150304-1.18363887e-01j -0.08705632-4.14856911e-

In [ ]:
gaussianMI(x,y,con,64)

[[-0.7997114 +0.29453853j]
 [ 0.5223441 -0.31063j   ]
 [-0.07055786+0.1778681j ]
 ...
 [ 0.6586639 +0.5730434j ]
 [-0.07055786+0.1778681j ]
 [-0.6318895 -0.6452211j ]]
tf.Tensor(
[[-5.13048351e-01+0.08648317j  1.89760387e+00+0.31411442j
   2.60458261e-01+0.95052946j ...  1.31133604e+00+3.0288694j
   2.60458261e-01+0.95052946j  3.14997882e-03-0.10075078j]
 [-3.90475392e-01+2.5773609j  -3.27396631e+00-0.9855423j
  -1.69321394e+00+0.8676196j  ... -7.29723096e-01-0.7673026j
  -1.69321394e+00+0.8676196j  -3.89966130e+00+3.8295908j ]
 [ 1.09564781e+00-1.0826341j   1.24217346e-02-0.04651693j
   4.95423675e-02-0.29727536j ... -4.66220379e-01+0.46552947j
   4.95423675e-02-0.29727536j  7.41560400e-01+0.9179509j ]
 ...
 [ 2.59168535e-01+0.19867541j  3.29385138e+00-1.5710967j
   1.60924375e+00+0.16994643j ...  3.78467059e+00+1.847844j
   1.60924375e+00+0.16994643j -6.91682100e-02-1.0722744j ]
 [ 3.60803032e+00-4.4726624j   5.22751212e-01-0.7210671j
   1.21348476e+00-2.6302016j  ... -1.22671151e+00

In [ ]:
tf.concat([[1],[1]],0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>